import { Book } from '../../../models/card.model';

export const books: Book[] = [
  {
    id: 1,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 2,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 3,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 4,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 5,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 6,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 7,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 8,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 9,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 10,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 11,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book2.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
  {
    id: 12,
    price: 12,
    title: 'The Title',
    author: 'The Author',
    cover_url: 'assets/book1.png',
    genre: 'The Genre',
    language: 'eng',
    created_date: '12.12.2022',
  },
];
